/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["Get haha"];
  };
  "/notes/": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["Note"][];
          };
        };
      };
    };
    post: operations["create note"];
  };
  "/notes/create": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["Note"];
          };
        };
      };
    };
  };
  "/notes/{id}": {
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateNoteRequest: {
      title?: string | null;
      content?: string | null;
    };
    Note: {
      /** Format: int32 */
      id?: number;
      content?: string | null;
      title?: string | null;
      done?: boolean;
    };
    SampleResponse: {
      name?: string | null;
      /** Format: int32 */
      age?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  "Get haha": {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["SampleResponse"];
        };
      };
    };
  };
  "create note": {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateNoteRequest"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["Note"];
        };
      };
    };
  };
}
