/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["Get haha"];
  };
  "/products/": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": (components["schemas"]["Note"])[];
          };
        };
      };
    };
  };
  "/products/create": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": components["schemas"]["Note"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Note: {
      /** Format: int32 */
      id?: number;
      content?: string | null;
      title?: string | null;
      done?: boolean;
    };
    SampleResponse: {
      name?: string | null;
      /** Format: int32 */
      age?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  "Get haha": {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["SampleResponse"];
        };
      };
    };
  };
}
